### ISSUE TITLE
Degrid Hanging

### ISSUE THREAD

**Issue by joesbright** [saopicc/DDFacet#29]
Hi all,

I'm trying to run DDFacet on a relatively small (17 GB) GMRT L-band dataset as a precursor to doing some direction dependent calibration. This is the first time I've run on this particular cluster so I'm just making a test image with very basic parameters (see attached log). I get as far as degridding the first data chunk, but this seems to hang indefinitely.

I'm still playing with the chunk size (I have it set quite small to avoid any memory issues), and in future I'll have to ask the sysadmin to up the shared memory allocation.

I'm running through singularity using the stimela version (DDF version 0.4.1.0)

Many thanks for any help/suggestions,

Best,
Joe

[ddf_github.log](https://github.com/saopicc/DDFacet/files/6911524/ddf_github.log)

**Comment by bennahugo** [comment]
```
 - 11:51:06 - DDFacet            |  - NBand ............................................. = 1
 - 11:51:06 - DDFacet            |  - NDegridBand ....................................... = 0
```
your problem is here - 0 means one degridband per database channel. Therefore you are likely blowing your memory budget. Judging by the frequency range I would say a minimum of 6-7 image bands and perhaps 10-14 degridding bands are needed.

Also please note we no longer support this version of DDFacet, nor Python 2.7. If you are looking to DD cal I would recommend you use DDFacet 0.6.0 and kMS 3.0.0.1. You need to use the tied version of these two packages - ie. kms 2.x will not work with DDFacet < 0.5. I would recommend you stick with the latest versions though. There were significant bug fixes. There is a wiki with a simple meerkat example which you could adapt). good luck

**Comment by joesbright** [comment]
Thanks a lot Ben, I appreciate the feedback and suggestions!
